name: macOS build
on:
  push:
    branches:
      - dev
      - patch**
      - newlocallab
  pull_request:
    branches:
      - dev
      - newlocallab
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
           date -u
           mkdir build
           date +%s > build/stamp
           brew uninstall --ignore-dependencies libtiff
           brew install libtiff gtk+3 gtkmm3 gtk-mac-integration adwaita-icon-theme libsigc++@2 little-cms2 libiptcdata fftw lensfun expat libomp shared-mime-info | tee -a depslog
           brew unlink libomp
           curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/fb8323f2b170bd4ae97e1bac9bf3e2983af3fdb0/Formula/libomp.rb
           brew install ./libomp.rb
           rm -f ./libomp.rb
           date -u
           echo "----====Pourage====----"
           cat depslog | grep Pouring
           zsh -c 'echo "Completed installation of dependencies in $(printf "%0.2f" $(($[$(date +%s)-$(cat build/stamp)]/$((60.))))) minutes"'
      - name: Configure build system
        env:
          CMAKE_CXX_STANDARD: 11
          PKG_CONFIG_PATH: /usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig
          RAW_THERAPEE_MAJOR: '5'
          RAW_THERAPEE_MINOR: '8'
          C_FLAGS: >
            -arch arm64 -mtune=generic -Xpreprocessor -fopenmp /usr/local/lib/libomp.dylib -I/usr/local/include -I/usr/local/opt/gdk-pixbuf/include -I/usr/local/opt/libiconv/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/expat/include -I/usr/local/opt/libtiff/include
        run: |
          cd build && date -u && date +%s > configstamp
          export C_FLAGS=$(echo -e $C_FLAGS | tr -d '\n')
          cmake -DCMAKE_BUILD_TYPE="Release" \
                -DPROC_TARGET_NUMBER="2" \
                -DCMAKE_EXE_LINKER_FLAGS="-L. -L/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -L/usr/local/opt/gdk-pixbuf/lib -L/usr/local/opt/libiconv/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/expat/lib" \
                -DCODESIGNID="Apple Development: andre@clarin.eu (LD66Z2PUV6)" \
                -DCACHE_NAME_SUFFIX="${RAW_THERAPEE_MAJOR}.${RAW_THERAPEE_MINOR}-${REF}" \
                -DLENSFUNDBDIR="/Applications/RawTherapee.app/Contents/Resources/share/lensfun" \
                -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
                -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ \
                -DCMAKE_C_FLAGS="-arch arm64 -Wno-pass-failed -Wno-deprecated-register -Wno-unused-command-line-argument" \
                -DCMAKE_CXX_FLAGS="-arch arm64 -Wno-pass-failed -Wno-deprecated-register -Wno-unused-command-line-argument" \
                -DOpenMP_C_FLAGS="${C_FLAGS}" \
                -DOpenMP_CXX_FLAGS="${C_FLAGS}" \
                -DOpenMP_C_LIB_NAMES=libomp \
                -DOpenMP_CXX_LIB_NAMES=libomp \
                -DOpenMP_libomp_LIBRARY=/usr/local/lib/libomp.dylib \
                -DWITH_LTO="ON" \
                -DCMAKE_AR=/usr/bin/ar \
                -DCMAKE_RANLIB=/usr/bin/ranlib \
                -DCMAKE_OSX_DEPLOYMENT_TARGET="12" \
                ..
            zsh -c 'echo "Configured in $(printf "%0.2f" $(($[$(date +%s)-$(cat configstamp)]/$((60.))))) minutes"'
      - name: Compile RawTherapee
        run: |
          date -u && date +%s > build/compilestamp
          cd build
          export REF=${GITHUB_REF##*/}
          make -j$(sysctl -a | grep machdep.cpu.thread_count | tail -c 2) install
          zsh -c 'echo "Compiled in $(printf "%0.2f" $(($[$(date +%s)-$(cat compilestamp)]/$((60.))))) minutes"'
      - name: Create application bundle
        run: |
          zsh
          date +%s > build/bundlestamp && date -u && cd build
          export REF=${GITHUB_REF##*/} && export LOCAL_PREFIX=/usr && make macosx_bundle
          export ARTIFACT=(RawTherapee*.zip)
          echo "=== artifact: ${ARTIFACT}"
          # defining environment variables for next step as per
          # https://github.com/actions/starter-workflows/issues/68
          echo "ARTIFACT_PATH=${GITHUB_WORKSPACE}/build/${ARTIFACT}" >> $GITHUB_ENV
          echo "ARTIFACT_FILE=${ARTIFACT}" >> $GITHUB_ENV
          zsh -c 'echo "Bundled in $(printf "%0.2f" $(($[$(date +%s)-$(cat bundlestamp)]/$((60.))))) minutes"'
          exit
      - uses: actions/upload-artifact@v2
        with:
          name: ${{env.ARTIFACT_FILE}}
          path: ${{env.ARTIFACT_PATH}}
      - name: Finish build
        run: |
          date -u
          zsh -c 'echo "Build completed in $(printf "%0.2f" $(($[$(date +%s)-$(cat build/stamp)]/$((60.))))) minutes"'
